def remove_punc_digits(text):
    exclude_chars = set(string.punctuation) - set('.0123456789')
    return ''.join(char for char in text if char not in exclude_chars)

def replace_digits_with_words(text):
    # Define a dictionary mapping digits to their Turkish word equivalents
    digit_mapping = {
        '0': 'sıfır',
        '1': 'bir',
        '2': 'iki',
        '3': 'üç',
        '4': 'dörd',
        '5': 'beş',
        '6': 'altı',
        '7': 'yeddi',
        '8': 'səkkiz',
        '9': 'doqquz',
        '10': 'on',
        '11': 'on bir',
        '12': 'on iki',
        '13': 'on üç',
        '14': 'on dörd',
        '15': 'on beş',
        '16': 'on altı',
        '17': 'on yeddi',
        '18': 'on səkkiz',
        '19': 'on doqquz',
        '20': 'iyirmi',
        '21': 'iyirmi bir',
        '22': 'iyirmi iki',
        '23': 'iyirmi üç',
        '24': 'iyirmi dörd',
        '25': 'iyirmi beş',
        '26': 'iyirmi altı',
        '27': 'iyirmi yeddi',
        '28': 'iyirmi səkkiz',
        '29': 'iyirmi doqquz',
        '30': 'otuz',
        '31': 'otuz bir',
        '32': 'otuz iki',
        '33': 'otuz üç',
        '34': 'otuz dörd',
        '35': 'otuz beş',
        '36': 'otuz altı',
        '37': 'otuz yeddi',
        '38': 'otuz səkkiz',
        '39': 'otuz doqquz',
        '40': 'qırx',
        '41': 'qırx bir',
        '42': 'qırx iki',
        '43': 'qırx üç',
        '44': 'qırx dörd',
        '45': 'qırx beş',
        '46': 'qırx altı',
        '47': 'qırx yeddi',
        '48': 'qırx səkkiz',
        '49': 'qırx doqquz',
        '50': 'əlli',
        '51': 'əlli bir',
        '52': 'əlli iki',
        '53': 'əlli üç',
        '54': 'əlli dörd',
        '55': 'əlli beş',
        '56': 'əlli altı',
        '57': 'əlli yeddi',
        '58': 'əlli səkkiz',
        '59': 'əlli doqquz',
        '60': 'altmış',
        '61': 'altmış bir',
        '62': 'altmış iki',
        '63': 'altmış üç',
        '64': 'altmış dörd',
        '65': 'altmış beş',
        '66': 'altmış altı',
        '67': 'altmış yeddi',
        '68': 'altmış səkkiz',
        '69': 'altmış doqquz',
        '70': 'yetmiş',
        '71': 'yetmiş bir',
        '72': 'yetmiş iki',
        '73': 'yetmiş üç',
        '74': 'yetmiş dörd',
        '75': 'yetmiş beş',
        '76': 'yetmiş altı',
        '77': 'yetmiş yeddi',
        '78': 'yetmiş səkkiz',
        '79': 'yetmiş doqquz',
        '80': 'səksən',
        '81': 'səksən bir',
        '82': 'səksən iki',
        '83': 'səksən üç',
        '84': 'səksən dörd',
        '85': 'səksən beş',
        '86': 'səksən altı',
        '87': 'səksən yeddi',
        '88': 'səksən səkkiz',
        '89': 'səksən doqquz',
        '90': 'doxsan',
        '91': 'doxsan bir',
        '92': 'doxsan iki',
        '93': 'doxsan üç',
        '94': 'doxsan dörd',
        '95': 'doxsan beş',
        '96': 'doxsan altı',
        '97': 'doxsan yeddi',
        '98': 'doxsan səkkiz',
        '99': 'doxsan doqquz',
        '100': 'yüz'
    }

    # Replace digits in the text with their Turkish word equivalents
    for digit, word in digit_mapping.items():
        text = text.replace(digit, word)

    return text

